### ISSUE TITLE
请问谁有USBX 虚拟串口的demo，who has USBX VCP demo，pls？

### ISSUE THREAD

**Issue by he2002512** [eclipse-threadx/samples#12]
最近想用usbx做stm32f103 的虚拟串口，没找到相关资料，请问谁有相关资料或者Demo，谢谢！

**Comment by xiaocq2001** [comment]
目前对stm32f103还没有直接可以使用的demo，关于cdc acm虚拟串口的使用可以参考user guide的说明：
https://docs.microsoft.com/en-us/azure/rtos/usbx/usbx-device-stack-5
