### ISSUE TITLE
problem in opening Azure_RTOS_6.1_STM32F746G-DISCO_IAR_Samples_2020_10_10.zip sample with IAR IDE

### ISSUE THREAD

**Issue by armembedded** [eclipse-threadx/samples#13]
Hi 
when I want to open an "Azure_RTOS_6.1_STM32F746G-DISCO_IAR_Samples_2020_10_10.zip" sample with IAR IDE, the IDE show a problem and also do not compile completely. 

IAR Version: 8.30
![Screenshot 2020-12-30 065444](https://user-images.githubusercontent.com/16489088/103327936-feb28300-4a6b-11eb-83a9-e41f9885ebcf.jpg)

**Comment by bochen-1** [comment]
Hi @armembedded, given the project was created by IAR 8.50.1, could you upgrade your IAR and try again?

**Comment by bochen-1** [comment]
Hi @armembedded I guess you already fixed it, so I close this issue.
