### ISSUE TITLE
Request to upgrade threadx to 6.1.3

### ISSUE THREAD

**Issue by mrrajeshrai** [eclipse-threadx/samples#16]
Hi Team,

The threadx module is updated to 6.1.3. Do you have any plan to upgrade the same with same as well? 

Thanks,
Rajesh

**Comment by goldscott** [comment]
We're not going to update the samples every patch release - that's just too much work. But you can update your sample project if you feel like it.

**Comment by mrrajeshrai** [comment]
On it. Thanks
