### ISSUE TITLE
example request

### ISSUE THREAD

**Issue by tomyqg** [eclipse-threadx/samples#2]
is there any example project for SAMA5D2 and SAM9X6?

**Comment by goldscott** [comment]
We do have generic ThreadX support for the Cortex-A5 and the ARM926EJ-S architectures, which should migrate easily to these particular implementations. We also support the most popular ARM development tools, e.g., IAR, ARM, GCC, etc.  We will be adding these generic ports to Github going forward.

We also recommend that you reach out to azure-rtos-sales@microsoft.com to initiate a deeper discussion on this.
