### ISSUE TITLE
Example project for STM32F4 series

### ISSUE THREAD

**Issue by BhuvaHiren** [eclipse-threadx/samples#24]
Hi,

Do we have any example project for stm32F4 series for stmcubeide?

Thanks,
Hiren Bhuva

**Comment by TiejunZhou-CN** [comment]
No we don’t. ST is plan for F4 series integration in Q2. See plan here, https://www.st.com/content/ccc/resource/sales_and_marketing/presentation/product_presentation/group1/5b/4f/89/bf/8f/18/4e/83/Microcontrollers_STM32Cube_AzureRTOS/files/Microcontrollers_STM32Cube_AzureRTOS.pdf/jcr:content/translations/en.Microcontrollers_STM32Cube_AzureRTOS.pdf
