### ISSUE TITLE
Renesas Cloud Kit to use standard netduox lib

### ISSUE THREAD

**Issue by shu-liu1314** [eclipse-threadx/samples#26]
Hi,
Can the Renesas cloud kit use the standard Netduox dns, http, sntp, etc, instead of using the customized functions in the sdk project with the wifi driver? Renesas_RSK_2MB board uses the standard netduox.

**Comment by ghost** [comment]
I am afraid not unless the wi-fi module supports bypass mode , as the wi-fi module has integrated the TCP/IP.

**Comment by TiejunZhou-CN** [comment]
@wangwen-ms is correct for the current sample project. Since Azure RTOS 6.1.8 release, there is a new feature called TCP/IP offload. We are working with Renesas to upgrade WIFI driver to support it. Once it is done, most of NetXDuo addons can be enabled seamlessly.
