### ISSUE TITLE
CoAP protocol support and sample application request

### ISSUE THREAD

**Issue by shrinivasragolu** [eclipse-threadx/samples#28]
Hi,

I have recently started using the Azure RTOS NetXDuo stack. Regarding MQTT, I could get protocol implementation and APIs to write an MQTT application. But now my requirement is to write a CoAP application using CoAP APIs. 

When I search in NetxDuo, I only find LWM2M, which is based on CoAP but not clean CoAP stand-alone implementation and samples.

Please help me with your pointers, that where can I get the CoAP implementation and sample application

Thanks in advance,
Srinivas.

**Comment by bochen-1** [comment]
Hi @shrinivasragolu You are right, our CoAP is used by LwM2M for now, we are also planning to implement CoAP stand-alone. Could you give more details about your applications? will you involve upper layer application in your project? such as: LwM2M, Thread, or other Applications. Then we can re-prioritize our tasks.

**Comment by srinivas1506** [comment]
Hi @bo-ms, 

Thanks for response. YES. We are a semiconductor company producing MCUs. We are using Threadx NetxDuo stack for networking and we need similar standalone support as provided for MQTT(standalone). Most of the customers have their own IoT platforms and they expect the CoAP application on my MCU should connect to their CoAP server securely. 

Hence, I am requesting you to provide similar support as MQTT. This is the request from most of the customers.

Could you please support standalone CoAP protocol implementation? Let me know if I miss something to answer your query.

Thanks,
Srinivas.

**Comment by bochen-1** [comment]
Hi @shrinivasragolu, thanks for sharing the info, we will discuss it internally, and will let you know when we have plan about it.

**Comment by srinivas1506** [comment]
@bo-ms, Thank you so much for support.

**Comment by bochen-1** [comment]
We did discuss it recently but CoAP was not prioritized. Thanks.
