### ISSUE TITLE
Secure TLS session start does NOT connect to IoT Hub

### ISSUE THREAD

**Issue by dsilva-vd** [eclipse-threadx/samples#32]
Hi I'm running the Azure ADU sample on a STM32F4 board (Ethernet)

My connection to my Iot Hub fails during the Secure TLS connect.

In the call to nx_secure_tls_session_start() the function returns 56. I cannot find a definition for that error code. Is there a suggestion on what to look into. 

Here is the console output for my program

Nx_SNTP_Client application started..
STM32 IpAddress: XXX.XXX.XXX.XXX 
SNTP client connected to NTP server : < ca.pool.ntp.org > 

SNTP update :
Mar 21, 2022 22:55:27.579 UTC 

21-03-2022 / 22:55:27
[INFO] Azure IoT Security Module has been enabled, status=0
IoTHub Host Name: my_az_hub.azure-devices.net; Device ID: stm32F429_engg1.
Disconnected from IoTHub!: error code = 0x00010005
Failed on nx_azure_iot_pnp_client_connect!
[INFO] Azure IoT Security Module has been disabled, status=0

**Comment by liydu** [comment]
@dsilva-vd, `0x10005` is MQTT connect failure error:
https://github.com/azure-rtos/netxduo/blob/1eee883def078a91b8cd19159d1796e3a8862814/addons/mqtt/nxd_mqtt_client.h#L282

There are a couple of things you can check:
* Network connection. Can try with a different Ethernet connection to see if the problem persists. For example, if the network has a proxy, it might cause this problem.
* Check the credentials for the IoT Hub device were correct.
